ktlint:
  FunctionExpressionBody:
    active: false
  NoBlankLineInList:
    active: false
  ChainMethodContinuation:
    active: false
  NoEmptyFirstLineInClassBody:
    active: false
  ClassSignature:
    active: false
  BlankLineBeforeDeclaration:
    active: false
  PropertyName:
    active: false
