[versions]
detekt = "2.0.0-alpha.6"
kotlin = "2.4.20"
kotlinx-benchmark = "0.5.0"

[libraries]
assertk = { module = "com.willowtreeapps.assertk:assertk", version = "0.28.1" }
detekt-ktlint = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }
kotlinx-benchmark-runtime = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }

[plugins]
kotlin-gradlePluginJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
gradleVersionsPlugin = { id = "com.github.ben-manes.versions", version = "0.62.0" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.37.0" }
